# Generated by Django 2.0.10 on 2019-03-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20190217_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('invitation_date', models.DateTimeField()),
                ('acceptation_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Accept')], max_length=1, verbose_name='Status')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='school.School')),
            ],
        ),
    ]
