# Generated by Django 2.0.10 on 2019-03-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='acceptation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
