# Generated by Django 2.0.10 on 2019-03-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20190328_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('r', 'Reviewed'), ('e', 'Enrolled')], default='p', max_length=1, verbose_name='Status'),
        ),
    ]
