# Generated by Django 2.0.10 on 2019-04-11 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20190331_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='participant',
            new_name='user',
        ),
    ]
